# Generated by Django 4.2.6 on 2024-02-10 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='article',
            new_name='article_comment',
        ),
    ]
